version: '3.8'

services:
  config-service:
    build: ./config-service
    container_name: config-cont
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - micro-network

  db-mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: restaurant_order_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - micro-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-cont
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - ORDER_SERVICE_URL=http://order-service:8081
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8082
    depends_on:
      config-service:
        condition: service_healthy
      loki:                  
        condition: service_started
    networks:
      - micro-network

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-cont
    ports:
      - "8082:8082"
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/restaurant_order_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRINGDOC_SERVER_URL=http://localhost:8080
    depends_on:
      db-mysql:
        condition: service_healthy
      config-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      loki:                  
        condition: service_started
    networks:
      - micro-network

  order-service:
    build: ./order-services
    container_name: order-cont
    ports:
      - "8081:8081"
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      #- "loki.url=http://loki:3100/loki/api/v1/push"
      #- "logging.config=classpath:logback-spring.xml"
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/restaurant_order_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRINGDOC_SERVER_URL=http://localhost:8080
    depends_on:
      db-mysql:
        condition: service_healthy
      config-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      loki:                  
        condition: service_started
    networks:
      - micro-network

  adminer:
    image: adminer
    container_name: adminer-cont
    ports:
      - "8085:8080"
    networks:
      - micro-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro-network
      
  # Vezbe 11
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    ports:
      - "9411:9411"
    networks:
      - micro-network
    # Opciono: kontejner se sam restartuje ako pukne
    restart: always
    
  # --- CENTRALNA BAZA ZA LOGOVE ---
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - micro-network

  # --- GRAFIČKI INTERFEJS ZA PRETRAGU LOGOVA I GRAFIKONE ---
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Korisničko ime i šifra će biti admin/admin
    networks:
      - micro-network
    depends_on:
      - loki

networks:
  micro-network:
    driver: bridge

volumes:
  mysql_data:
