resilience4j.circuitbreaker.instances.restaurantServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.restaurantServiceCB.waitDurationInOpenState=10000ms
resilience4j.ratelimiter.instances.restaurantServiceRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.restaurantServiceRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.restaurantServiceRateLimiter.timeout-duration=50
custom.welcome-message=Dobrodosli u Order sistem v6!