resilience4j.circuitbreaker.instances.restaurantServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.restaurantServiceCB.waitDurationInOpenState=10000ms
custom.welcome-message=Dobrodosli u Order sistem v6!