spring.application.name=gateway-service
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/*/orders/**

spring.cloud.gateway.server.webflux.routes[1].id=restaurant-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/*/restaurants/**

# Ostalo ostaje isto
springdoc.swagger-ui.urls[0].name=Order Service
springdoc.swagger-ui.urls[0].url=/api/*/orders/v3/api-docs

springdoc.swagger-ui.urls[1].name=Restaurant Service
springdoc.swagger-ui.urls[1].url=/api/*/restaurants/v3/api-docs

spring.cloud.gateway.server.webflux.globalcors.add-to-idp-col-mappings=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:8080, http://localhost:8081, http://localhost:8082
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
