spring.application.name=order-services
server.port=8081

# H2 Baza u memoriji
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate pode?avanja
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# automatski pravi tabele u bazi na osnovu Java klasa (@Entity)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Da se baza popuni podacima
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Pristup bazi preko browsera na http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.h2.console.settings.web-allow-others=true

# Swagger putanja
springdoc.swagger-ui.path=/swagger-ui.html

#v4
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-binding-errors=always

# Konfiguracija instance osiguraca
resilience4j.circuitbreaker.instances.restaurantServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.restaurantServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.restaurantServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.restaurantServiceCB.permittedNumberOfCallsInHalfOpenState=3

# Eksponiranje Actuator endpoint-a
#management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Povezivanje Resilience4j sa Health sistemom
resilience4j.circuitbreaker.instances.restaurantServiceCB.registerHealthIndicator=true

# Opciono: Smanjenje prenatrpanosti logova za Feign i Resilience4j
logging.level.org.springframework.cloud.openfeign=WARN
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
#logging.file.name=logs/order-service.log
# Da se vidi tacno sta Resilience4j radi
logging.level.io.github.resilience4j=DEBUG

#v5
springdoc.api-docs.path=/api/*/orders/v3/api-docs

# Dozvoljava Swagger-u sa porta 8080 da povuce dokumentaciju
springdoc.api-docs.enabled=true
springdoc.server.url=http://localhost:8080
management.endpoints.web.cors.allowed-origins=http://localhost:8080
management.endpoints.web.cors.allowed-methods=GET,POST,PUT,DELETE

#v6

spring.cloud.config.uri=http://localhost:8888
# Objedinjeni Actuator endpointi (za zdravlje, CB i refresh configa)
management.endpoints.web.exposure.include=health,circuitbreakers,refresh