spring.application.name=order-services
server.port=8081

# H2 Baza u memoriji
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate pode?avanja
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# automatski pravi tabele u bazi na osnovu Java klasa (@Entity)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Da se baza popuni podacima
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Pristup bazi preko browsera na http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.h2.console.settings.web-allow-others=true

# Swagger putanja
springdoc.swagger-ui.path=/swagger-ui.html