spring.application.name=config-service
server.port=8888
spring.cloud.config.server.native.search-locations=file:/home/ivana-milutinovic/Documents/RAF/2025-26/Letnji/PS/PS-vezbe/config_repo/

spring.cloud.config.server.accept-empty=false
spring.profiles.active=native
