spring.application.name=config-service
server.port=8888

# Putanja do repozitorijuma
spring.cloud.config.server.git.uri=https://github.com/ivanna1109/PS-vezbe.git
# Putanja do foldera unutar repozitorijuma
spring.cloud.config.server.git.search-paths=config_repo
# Branch
spring.cloud.config.server.git.default-label=main